# Generated by Django 5.1.1 on 2024-09-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, db_column='ATC')),
            ],
        ),
        migrations.CreateModel(
            name='NetherlandsDrug',
            fields=[
                ('numer_rejestracyjny', models.TextField(blank=True, db_column='NUMER REJESTRACYJNY', null=True)),
                ('rodzaj', models.TextField(blank=True, db_column='RODZAJ', null=True)),
                ('nazwa_produktu', models.TextField(blank=True, db_column='NAZWA PRODUKTU', null=True)),
                ('podmiot_odpowiedzialny', models.TextField(blank=True, db_column='PODMIOT ODPOWIEDZIALNY', null=True)),
                ('status_dostawy', models.TextField(blank=True, db_column='STATUS DOSTAWY', null=True)),
                ('forma_leku', models.TextField(blank=True, db_column='FORMA LEKU', null=True)),
                ('trasa', models.TextField(blank=True, db_column='TRASA', null=True)),
                ('atc', models.OneToOneField(blank=True, db_column='ATC', default=0, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='leki.atc')),
            ],
        ),
        migrations.CreateModel(
            name='PolandDrug',
            fields=[
                ('numer_rejestracyjny', models.TextField(blank=True, db_column='NUMER REJESTRACYJNY', null=True)),
                ('nazwa_produktu', models.TextField(blank=True, db_column='NAZWA PRODUKTU', null=True)),
                ('podmiot_odpowiedzialny', models.TextField(blank=True, db_column='PODMIOT ODPOWIEDZIALNY', null=True)),
                ('forma_leku', models.TextField(blank=True, db_column='FORMA LEKU', null=True)),
                ('trasa', models.TextField(blank=True, db_column='TRASA', null=True)),
                ('atc', models.OneToOneField(blank=True, db_column='ATC', default=0, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='leki.atc')),
            ],
        ),
    ]
